### ISSUE TITLE
Hello, I'm running :bash install_colmapforvissat.sh and I'm getting the following error:

### ISSUE THREAD

**Issue by AcoderSc** [Kai-46/SatelliteSfM#11]
Traceback (most recent call last):
  File "ColmapForVisSat/scripts/python/build.py", line 545, in <module>
    main()
  File "ColmapForVisSat/scripts/python/build.py", line 524, in main
    build_glew(args)
  File "ColmapForVisSat/scripts/python/build.py", line 314, in build_glew
    download_zipfile(url, archive_path, args.build_path,
  File "ColmapForVisSat/scripts/python/build.py", line 189, in download_zipfile
    urllib.request.urlretrieve(url, archive_path)
  File "/home/cver/anaconda3/envs/SatelliteSfM/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/cver/anaconda3/envs/SatelliteSfM/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/cver/anaconda3/envs/SatelliteSfM/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/cver/anaconda3/envs/SatelliteSfM/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/cver/anaconda3/envs/SatelliteSfM/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/cver/anaconda3/envs/SatelliteSfM/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/cver/anaconda3/envs/SatelliteSfM/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
It seems that the follow link is broken:
![image](https://github.com/Kai-46/SatelliteSfM/assets/90641643/2602ade6-8524-4902-b8a2-facad483ed91)

**Comment by hzlajojo** [comment]
I downloaded this zipfile with this link: 
`url = "https://sourceforge.net/projects/glew/files/glew/2.1.0/glew-2.1.0.zip/download"`
