### ISSUE TITLE
I have a problem using satellite_sfm.py

### ISSUE THREAD

**Issue by ouyuanzheng** [Kai-46/SatelliteSfM#9]
I have a problem using satellite_sfm.py
The error is reported as follows:
(SatelliteSfM) root@LAPTOP-MOJP7CII:/mnt/d/SatelliteSfM/SatelliteSfM# python satellite_sfm.py --input_folder examples/inputs --output_folder examples/outputs --run_sfm [--use_srtm4] [--enable_debug]
Traceback (most recent call last):
  File "/root/anaconda3/envs/SatelliteSfM/lib/python3.8/site-packages/osgeo/__init__.py", line 30, in swig_import_helper    return importlib.import_module(mname)
  File "/root/anaconda3/envs/SatelliteSfM/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libpoppler.so.126: cannot open shared object file: No such file or directory
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "satellite_sfm.py", line 4, in <module>
    from preprocess.preprocess_image_set import preprocess_image_set
  File "/mnt/d/SatelliteSfM/SatelliteSfM/preprocess/preprocess_image_set.py", line 12, in <module>
    from preprocess.parse_tif_image import parse_tif_image
  File "/mnt/d/SatelliteSfM/SatelliteSfM/preprocess/parse_tif_image.py", line 3, in <module>
    from osgeo import gdal, gdalconst
  File "/root/anaconda3/envs/SatelliteSfM/lib/python3.8/site-packages/osgeo/__init__.py", line 46, in <module>
    _gdal = swig_import_helper()
  File "/root/anaconda3/envs/SatelliteSfM/lib/python3.8/site-packages/osgeo/__init__.py", line 43, in swig_import_helper    return importlib.import_module('_gdal')
  File "/root/anaconda3/envs/SatelliteSfM/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_gdal'
Last display：ModuleNotFoundError: No module named '_gdal'
But I have installed gdal，I can't solve it now. Do you have any suggestions？

**Comment by hzlajojo** [comment]
Hi, I have the same issue.
(For Ubuntu 20.04)
I think this might be helpful for you.
[[Installing Python-GDAL with OSGEO?](https://gis.stackexchange.com/questions/226928/installing-python-gdal-with-osgeo)](https://gis.stackexchange.com/questions/226928/installing-python-gdal-with-osgeo
)
Finally, it works for me:
conda install -c conda-forge gdal==3.3.2 (Or any other version received from ogrinfo)

**Comment by hzlajojo** [comment]
Hi, I have the same issue.
(For Ubuntu 20.04)
I think this might be helpful for you.
[Installing Python-GDAL with OSGEO?](https://gis.stackexchange.com/questions/226928/installing-python-gdal-with-osgeo)
Finally, it works for me:
conda install -c conda-forge gdal==3.3.2 (Or any other version received from ogrinfo)

**Comment by AcoderSc** [comment]
Hello, is SatelliteSfM installed successfully? I'm having some trouble
